### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by maandree** [dariost/GRainbow#1]
I get this error when I try to build grainbow-git from AUR

```
grainbow.cpp:(.text.startup+0x209): undefined reference to `libgamma::Site::Site(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
```

**Comment by dariost** [comment]
I've tried to install grainbow-git from the AUR in a clean Arch Linux system, and it works.

Are you using the same libgamma and libgammamm that are in the AUR or are you using a custom one?
What version of g++ are you using?

**Comment by maandree** [comment]
I thought I was using the versions in AUR, but I rebuilt them and it is working now.

---

I can confirm that multimonitor support.
